// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

// package db

// import (
// 	"database/sql"
// )

// type DBTX interface {
// 	ExecContext(ctx interface{ Done() <-chan struct{} }, query string, args ...interface{}) (sql.Result, error)
// 	PrepareContext(ctx interface{ Done() <-chan struct{} }, query string) (*sql.Stmt, error)
// 	QueryContext(ctx interface{ Done() <-chan struct{} }, query string, args ...interface{}) (*sql.Rows, error)
// 	QueryRowContext(ctx interface{ Done() <-chan struct{} }, query string, args ...interface{}) *sql.Row
// }

// func New(db DBTX) *Queries {
// 	return &Queries{db: db}
// }

// type Queries struct {
// 	db DBTX
// }

// func (q *Queries) WithTx(tx *sql.Tx) *Queries {
// 	return &Queries{db: tx}
// }
package db

import (
	"context"
	"database/sql"
)

type DBTX interface {
	ExecContext(ctx context.Context, query string, args ...interface{}) (sql.Result, error)
	PrepareContext(ctx context.Context, query string) (*sql.Stmt, error)
	QueryContext(ctx context.Context, query string, args ...interface{}) (*sql.Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{db: tx}
}