// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, dob)
VALUES ($1, $2)
RETURNING id, name, dob
`

func (q *Queries) CreateUser(ctx context.Context, name string, dob time.Time) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, name, dob)
	var u User
	err := row.Scan(&u.ID, &u.Name, &u.Dob)
	return u, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, dob FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var u User
	err := row.Scan(&u.ID, &u.Name, &u.Dob)
	return u, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET name = $1, dob = $2 WHERE id = $3 RETURNING id, name, dob
`

func (q *Queries) UpdateUser(ctx context.Context, name string, dob time.Time, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, name, dob, id)
	var u User
	err := row.Scan(&u.ID, &u.Name, &u.Dob)
	return u, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, dob FROM users ORDER BY id LIMIT $1 OFFSET $2
`

func (q *Queries) ListUsers(ctx context.Context, limit, offset int32) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var users []User
	for rows.Next() {
		var u User
		if err := rows.Scan(&u.ID, &u.Name, &u.Dob); err != nil {
			return nil, err
		}
		users = append(users, u)
	}
	return users, rows.Err()
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}
